### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by vladbyk89**
what do you this about this as a start for the profile page?

### CODE REVIEW

**Comment by NikitaRossenko** [comment]
Can you please make a button with route in the main _Layout file? i'm using a phone and can't navigate straight to the profile page. just a temp button :)

**Comment by NikitaRossenko** [comment]
The code it self looks very clean and understandable by the way.

**Comment by vladbyk89** [comment]
made few changes

**Review by NikitaRossenko — APPROVED** [review]
Looks good for a start.

**Review by talyaron — APPROVED** [review]
look OK

**Pull request merged**
